### ISSUE TITLE
Question about Scale Normalization and Code Release Timeline

### ISSUE THREAD

**Issue by shim94kr** [eric-zqwang/puzzlefusion-plusplus#1]
First of all, I'd like to say that I thoroughly enjoyed reading your research—great job!

I have a question regarding the scale normalization in your study. Fractures that could originally fit together might not do so if their scales are changed. To address this, I see that you provided a scale factor as a condition to the model. Did you compare your model against a model without the scale factor condition, where the fractures were not normalized in scale? If so, did the model with the scale factor condition perform better?

Additionally, I am eager to see the visualization code and the data preparation code using JigSaw. Could you let me know when these will be available?

Thank you for your time, and I look forward to your response.

**Comment by eric-zqwang** [comment]
Hi,

Thanks for your interest! I'll address your question one by one.
1. The reason I use a scale factor is that during VQ-VAE training, each fracture is normalized. The denoiser takes this normalized point cloud latent, and without the scale factor, denoiser doesn't know the actual scale of the fracture.
2. Without normalizing the latent during VQ-VAE training, the quality of the latent decoded back to the point cloud is not good. Therefore, I haven't tried it without the normalization/scale factor.
3. For the visualization code, I'll organize it and release it in one or two weeks. If you need it sooner, please email me, and I can send you an unorganized version. The data preparation using Jigsaw is a bit messy, but if needed, I can also guide you on how to prepare the data and send you the relevant (unorganized) code.

Hope this helps to address your questions.

**Comment by shim94kr** [comment]
Thank you for your prompt response.

I understand you used scale normalization due to VQ-VAE training. While I see the reason, it would be interesting to test the assembly without it, since the original scale might improve the performance of assembly.

Meanwhile, regarding the denoiser, does the scale factor not get included there? For instance, I found data_dict['part_scale'] in denoniser. https://github.com/eric-zqwang/puzzlefusion-plusplus/blob/13e7a942933da1e9e5bbef9c8dc38265a37447cb/puzzlefusion_plusplus/denoiser/model/denoiser.py#L100-L108.

It's great to hear that the visualization code will be released soon. I will email you regarding the Jigsaw matching code, as I'm eager to see it.

Thanks again for your time and help!

**Comment by eric-zqwang** [comment]
The code has already used the original scale to test the assembly. The latent here is encoded by the normalized point cloud. So we need use this `data_dict['part_scale']` to denote the original fracture scale in the denoiser. If you don't use this scale condition, the denoiser will get a list of latent with the same scale because of normalization, and the model can not work.

**Comment by shim94kr** [comment]
I understand what you meant. Thank you for your answer.
