### ISSUE TITLE
Why is the input of Verify a histogram vector, which is puzzling and does not work on other data

### ISSUE THREAD

**Issue by fank996** [eric-zqwang/puzzlefusion-plusplus#2]

**Comment by eric-zqwang** [comment]
Can you explain more about your questions? What do you mean it does not work on other data? The histogram is derived from Jigsaw point matching results, and we simply use their results to construct this histogram, which represents the alignment features between two different fractures. We then input this histogram into a transformer to get the likelihood of alignment.
