### ISSUE TITLE
Verifier & Matching data generation

### ISSUE THREAD

**Issue by adeislam** [eric-zqwang/puzzlefusion-plusplus#3]
Hi, thank you for the work,when can you share the code to generate verifier and matching data?

**Comment by eric-zqwang** [comment]
Hi, 

Thank you for your interest in our work. At the moment, the code for generating verifier and matching data is not organized, and I am currently very busy. I aim to release it within a month.

In addition, the processed verifier data and matching data have already been released. You can download and use these data to run the code.

**Comment by adeislam** [comment]
Thank you for your response.
Yes, I have downloaded that data but code in case of we want to train on some other dataset than breaking bad.

Thank you,

**Comment by eric-zqwang** [comment]
Ah I see. The code for generating the verifier and matching data is built on the Jigsaw codebase. I'll organize it as soon as possible. Sorry for the inconvenience.

**Comment by adeislam** [comment]
Thank you, looking forward to it.

**Comment by AllendLi** [comment]
> Ah I see. The code for generating the verifier and matching data is built on the Jigsaw codebase. I'll organize it as soon as possible. Sorry for the inconvenience.

Very much thanks for your work, may i ask which part of code is used to generate the verifier & matching data in jigsaw?

**Comment by eric-zqwang** [comment]
> may i ask which part of code is used to generate the verifier & matching data in jigsaw?

You need to save the following key elements in `model/modules/matching_base_model.py`:
* gt_pcs: ground truth point cloud
* critical_pcs_idx: indices of segmented fracture surfaces by Jigsaw module
* correspondence: the matching points between fragments

These three components will enable the identification of matching points between the fragments. Afterward, post-processing will generate the verifier data and matching data.

**Comment by Louis-Leee** [comment]
hi Zhengqing,

Really impressive work! I also want to utilize your method on our own data, but we are stuck in the matching data generation, too. So the code release will be highly appreciated at your earliest convenience.  Thanks!

**Comment by eric-zqwang** [comment]
Hi Louis,

Apologies for the delay; I was busy with other things earlier. I'll be working on the generate matching data code now and will upload it within 1-2 days.

**Comment by eric-zqwang** [comment]
I've uploaded the matching data generation code in the `Jigsaw_matching` folder. Thanks again for your patience. I'll close this issue now, but if you run into any more problems, feel free to reopen it or start a new issue.
